"""create polymorphic articles

Revision ID: 138d1fa2b3d4
Revises: 235691aa0ca4
Create Date: 2019-11-17 18:56:35.517766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '138d1fa2b3d4'
down_revision = '235691aa0ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles_polymorphic',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('article_type', sa.Integer(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_articles_polymorphic'))
    )
    op.create_index(op.f('ix_articles_polymorphic_date'), 'articles_polymorphic', ['date'], unique=False)
    # ### end Alembic commands ###
    op.create_index(op.f('ix_articles_polymorphic_extra_slug'), 'articles_polymorphic', [sa.text("(extra->>'slug')")])
    op.create_index(op.f('ix_articles_polymorphic_extra_tags'), 'articles_polymorphic', [sa.text("(extra->'tags')")], postgresql_using="GIN")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_polymorphic_date'), table_name='articles_polymorphic')
    op.drop_table('articles_polymorphic')
    # ### end Alembic commands ###
    op.drop_index(op.f('ix_articles_polymorphic_extra_slug'), table_name='articles_polymorphic')
    op.drop_index(op.f('ix_articles_polymorphic_extra_tags'), table_name='articles_polymorphic')
