"""article with extra

Revision ID: 2d1fb1e0739f
Revises: fce41016df95
Create Date: 2019-11-15 18:03:15.091344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d1fb1e0739f'
down_revision = 'fce41016df95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles_with_extra',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_articles_with_extra'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles_with_extra')
    # ### end Alembic commands ###
