"""index article date

Revision ID: 4424b7c67f9c
Revises: 2d1fb1e0739f
Create Date: 2019-11-15 18:28:59.568786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4424b7c67f9c'
down_revision = '2d1fb1e0739f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_articles_with_extra_date'), 'articles_with_extra', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_with_extra_date'), table_name='articles_with_extra')
    # ### end Alembic commands ###
